# Jekyll config
# Intended for rarely-modified settings
# Not reloaded when served

# Site settings
title: James Zhu
email: your-email@example.com
description: >- # ignore newlines until "baseurl:"
  Your description here
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jameszhu.io"
github_username:  jameslzhu
github: [metadata]

# Build settings
markdown: CommonMarkGhPages
remote_theme: broccolini/swiss
theme_color: black
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-postcss
  - jekyll-purgecss

whitelist:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - postcss.config.js
  - LICENSE
  - README.md
