# Jekyll config
# Intended for rarely-modified settings
# Not reloaded when served

# Site settings
title: James Zhu
email: your-email@example.com
description: >- # ignore newlines until "baseurl:"
  Description here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jameszhu.io"
github_username:  jameslzhu
github: [metadata]

# Build settings
markdown: CommonMarkGhPages
# theme: minima
remote_theme: broccolini/swiss
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme

whitelist:
  - jekyll-redirect-from

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
